const plantas = [
    // ================= YA TENÍAS =================
    {
        nombre: "Acelga",
        categoria: "Comestible",
        humedad: "Media-Alta",
        meses: [1,2,3,4,5,6,7,8,9,10],
        estacion: "Todo el año",
        germina: 8,
        cosecha: 70,
        macetaMin: "20cm prof.",
        macetaIdeal: "30cm (15L)",
        tips: "Cosecha hojas externas. Alta en nitrógeno.",
        imgEtapa1: "https://images.unsplash.com/photo-1598112972545-84373a444ca0?auto=format&fit=crop&w=300",
        imgEtapa2: "https://images.unsplash.com/photo-1508500351473-883a6c0269f6?auto=format&fit=crop&w=300"
    },

    // ================= HOJAS =================
    {
        nombre: "Lechuga",
        categoria: "Comestible",
        humedad: "Media-Alta",
        meses: [2,3,4,5,6,7,8,9],
        estacion: "Otoño-Invierno",
        germina: 5,
        cosecha: 60,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Evitar calor fuerte.",
        imgEtapa1: "https://images.unsplash.com/photo-1559561853-08451507cbe7?auto=format&fit=crop&w=300",
        imgEtapa2: "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?auto=format&fit=crop&w=300"
    },
    {
        nombre: "Espinaca",
        categoria: "Comestible",
        humedad: "Media",
        meses: [3,4,5,6,7,8],
        estacion: "Invierno",
        germina: 7,
        cosecha: 50,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Crece rápido con frío.",
        imgEtapa1: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=300",
        imgEtapa2: "https://images.unsplash.com/photo-1604908177225-4e2c2c2d8ef1?auto=format&fit=crop&w=300"
    },
    {
        nombre: "Rúcula",
        categoria: "Comestible",
        humedad: "Media",
        meses: [2,3,4,5,6,7,8,9],
        estacion: "Otoño-Primavera",
        germina: 4,
        cosecha: 40,
        macetaMin: "10cm",
        macetaIdeal: "15cm",
        tips: "Muy rápida.",
        imgEtapa1: "https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?auto=format&fit=crop&w=300",
        imgEtapa2: "https://images.unsplash.com/photo-1603048297172-c92544798d5a?auto=format&fit=crop&w=300"
    },

    // ================= RAICES =================
    {
        nombre: "Zanahoria",
        categoria: "Raíz",
        humedad: "Media",
        meses: [3,4,5,6,7,8],
        estacion: "Invierno",
        germina: 10,
        cosecha: 90,
        macetaMin: "25cm",
        macetaIdeal: "30cm",
        tips: "Tierra suelta.",
        imgEtapa1: "https://images.unsplash.com/photo-1582515073490-dc6b9d1c7d5c?auto=format&fit=crop&w=300",
        imgEtapa2: "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?auto=format&fit=crop&w=300"
    },
    {
        nombre: "Remolacha",
        categoria: "Raíz",
        humedad: "Media",
        meses: [2,3,4,5,6,7],
        estacion: "Otoño",
        germina: 8,
        cosecha: 80,
        macetaMin: "20cm",
        macetaIdeal: "25cm",
        tips: "También hojas comestibles.",
        imgEtapa1: "https://images.unsplash.com/photo-1572441713132-51c75654db73?auto=format&fit=crop&w=300",
        imgEtapa2: "https://images.unsplash.com/photo-1615486369736-610e4a68b7a1?auto=format&fit=crop&w=300"
    },

    // ================= AROMATICAS =================
    {
        nombre: "Albahaca",
        categoria: "Aromática",
        humedad: "Media",
        meses: [9,10,11,12],
        estacion: "Verano",
        germina: 6,
        cosecha: 60,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "No soporta frío.",
        imgEtapa1: "https://images.unsplash.com/photo-1592928302636-c83cf1f9c8b3?auto=format&fit=crop&w=300",
        imgEtapa2: "https://images.unsplash.com/photo-1604908177225-4e2c2c2d8ef1?auto=format&fit=crop&w=300"
    },
    {
        nombre: "Romero",
        categoria: "Aromática",
        humedad: "Baja",
        meses: [3,4,5,9],
        estacion: "Todo el año",
        germina: 20,
        cosecha: 120,
        macetaMin: "20cm",
        macetaIdeal: "30cm",
        tips: "Muy resistente.",
        imgEtapa1: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=300",
        imgEtapa2: "https://images.unsplash.com/photo-1603048297172-c92544798d5a?auto=format&fit=crop&w=300"
    },
    {
        nombre: "Menta",
        categoria: "Aromática",
        humedad: "Alta",
        meses: [2,3,4,5,9,10],
        estacion: "Primavera",
        germina: 12,
        cosecha: 60,
        macetaMin: "20cm",
        macetaIdeal: "25cm",
        tips: "Muy invasiva.",
        imgEtapa1: "https://images.unsplash.com/photo-1628556270448-4d4e1f8a2d2b?auto=format&fit=crop&w=300",
        imgEtapa2: "https://images.unsplash.com/photo-1603048297172-c92544798d5a?auto=format&fit=crop&w=300"
    },

    // ================= FRUTOS =================
    {
        nombre: "Tomate",
        categoria: "Fruto",
        humedad: "Media",
        meses: [8,9,10,11],
        estacion: "Primavera-Verano",
        germina: 7,
        cosecha: 90,
        macetaMin: "30cm",
        macetaIdeal: "20L",
        tips: "Mucho sol.",
        imgEtapa1: "https://images.unsplash.com/photo-1592419044706-39796d40f98c?auto=format&fit=crop&w=300",
        imgEtapa2: "https://images.unsplash.com/photo-1561136594-7f68413baa99?auto=format&fit=crop&w=300"
    },
    {
        nombre: "Pepino",
        categoria: "Fruto",
        humedad: "Media-Alta",
        meses: [9,10,11],
        estacion: "Verano",
        germina: 5,
        cosecha: 70,
        macetaMin: "25cm",
        macetaIdeal: "30L",
        tips: "Necesita tutor.",
        imgEtapa1: "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?auto=format&fit=crop&w=300",
        imgEtapa2: "https://images.unsplash.com/photo-1582515073490-dc6b9d1c7d5c?auto=format&fit=crop&w=300"
    },

    // ================= FLORES =================
    {
        nombre: "Lavanda",
        categoria: "Flor / Decorativa",
        humedad: "Baja",
        meses: [3,4,9],
        estacion: "Primavera",
        germina: 15,
        cosecha: 120,
        macetaMin: "20cm",
        macetaIdeal: "30cm",
        tips: "Ama el sol.",
        imgEtapa1: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=300",
        imgEtapa2: "https://images.unsplash.com/photo-1474511014561-3c50cf38fd46?auto=format&fit=crop&w=300"
    },
    {
        nombre: "Girasol",
        categoria: "Flor / Decorativa",
        humedad: "Media",
        meses: [9,10,11],
        estacion: "Verano",
        germina: 7,
        cosecha: 90,
        macetaMin: "30cm",
        macetaIdeal: "40cm",
        tips: "Necesita sol pleno.",
        imgEtapa1: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=300",
        imgEtapa2: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=300"
    }

    ,
    {
        nombre: "Caléndula",
        categoria: "Flor / Decorativa",
        humedad: "Baja-Media",
        meses: [2,3,4,5,6,7,8],
        estacion: "Otoño-Invierno",
        germina: 10,
        cosecha: 90,
        macetaMin: "20cm",
        macetaIdeal: "25cm",
        tips: "Atrae polinizadores. Flor comestible.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Tomate Cherry",
        categoria: "Fruto",
        humedad: "Media",
        meses: [8,9,10,11],
        estacion: "Primavera-Verano",
        germina: 7,
        cosecha: 80,
        macetaMin: "30cm prof.",
        macetaIdeal: "Balde 20L",
        tips: "Necesita mucho sol y tutor.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Morrón",
        categoria: "Fruto",
        humedad: "Media",
        meses: [8,9,10,11],
        estacion: "Primavera-Verano",
        germina: 10,
        cosecha: 90,
        macetaMin: "25cm",
        macetaIdeal: "20L",
        tips: "Requiere calor, sol y buen drenaje.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Ají",
        categoria: "Fruto",
        humedad: "Media",
        meses: [8,9,10,11],
        estacion: "Primavera-Verano",
        germina: 12,
        cosecha: 100,
        macetaMin: "20cm",
        macetaIdeal: "15L",
        tips: "Necesita calor sostenido.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Berenjena",
        categoria: "Fruto",
        humedad: "Media",
        meses: [8,9,10],
        estacion: "Primavera",
        germina: 10,
        cosecha: 100,
        macetaMin: "25cm",
        macetaIdeal: "20L",
        tips: "Mucho sol y abrigo del viento.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Zapallito",
        categoria: "Fruto",
        humedad: "Media-Alta",
        meses: [9,10,11],
        estacion: "Primavera-Verano",
        germina: 6,
        cosecha: 60,
        macetaMin: "30cm",
        macetaIdeal: "40L",
        tips: "Necesita espacio y riego regular.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Zapallo",
        categoria: "Fruto",
        humedad: "Media-Alta",
        meses: [9,10,11],
        estacion: "Primavera-Verano",
        germina: 7,
        cosecha: 120,
        macetaMin: "35cm",
        macetaIdeal: "50L",
        tips: "Ideal si tiene mucho espacio para ramificar.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Zucchini",
        categoria: "Fruto",
        humedad: "Media-Alta",
        meses: [9,10,11],
        estacion: "Primavera-Verano",
        germina: 6,
        cosecha: 65,
        macetaMin: "30cm",
        macetaIdeal: "40L",
        tips: "Produce rápido con buen sol.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Melón",
        categoria: "Fruto",
        humedad: "Media",
        meses: [10,11,12],
        estacion: "Verano",
        germina: 8,
        cosecha: 110,
        macetaMin: "35cm",
        macetaIdeal: "50L",
        tips: "Necesita calor y mucho sol.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Sandía",
        categoria: "Fruto",
        humedad: "Media",
        meses: [10,11,12],
        estacion: "Verano",
        germina: 8,
        cosecha: 120,
        macetaMin: "40cm",
        macetaIdeal: "60L",
        tips: "Muy exigente en espacio y sol.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Frutilla",
        categoria: "Fruto",
        humedad: "Media",
        meses: [3,4,5,6],
        estacion: "Otoño",
        germina: 14,
        cosecha: 120,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Va muy bien en jardineras y colgantes.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Arveja",
        categoria: "Leguminosa",
        humedad: "Media",
        meses: [3,4,5,6,7],
        estacion: "Otoño-Invierno",
        germina: 7,
        cosecha: 80,
        macetaMin: "20cm",
        macetaIdeal: "25cm",
        tips: "Necesita guía o tutor liviano.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Haba",
        categoria: "Leguminosa",
        humedad: "Media",
        meses: [4,5,6,7],
        estacion: "Invierno",
        germina: 8,
        cosecha: 100,
        macetaMin: "25cm",
        macetaIdeal: "30cm",
        tips: "Muy buena para meses fríos.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Poroto Chaucha",
        categoria: "Leguminosa",
        humedad: "Media",
        meses: [9,10,11],
        estacion: "Primavera-Verano",
        germina: 6,
        cosecha: 60,
        macetaMin: "25cm",
        macetaIdeal: "30cm",
        tips: "Puede necesitar tutor según variedad.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Rabanito",
        categoria: "Raíz",
        humedad: "Media",
        meses: [2,3,4,5,6,7,8,9],
        estacion: "Otoño-Primavera",
        germina: 4,
        cosecha: 30,
        macetaMin: "12cm",
        macetaIdeal: "15cm",
        tips: "Muy rápido, ideal para principiantes.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Nabo",
        categoria: "Raíz",
        humedad: "Media",
        meses: [3,4,5,6,7,8],
        estacion: "Invierno",
        germina: 6,
        cosecha: 60,
        macetaMin: "20cm",
        macetaIdeal: "25cm",
        tips: "Prefiere clima fresco.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Papa",
        categoria: "Tubérculo",
        humedad: "Media",
        meses: [8,9,10],
        estacion: "Primavera",
        germina: 15,
        cosecha: 120,
        macetaMin: "30cm",
        macetaIdeal: "Bolsa 40L",
        tips: "Conviene aporcar a medida que crece.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Batata",
        categoria: "Tubérculo",
        humedad: "Media",
        meses: [10,11,12],
        estacion: "Verano",
        germina: 15,
        cosecha: 140,
        macetaMin: "30cm",
        macetaIdeal: "40L",
        tips: "Necesita bastante calor.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Cebolla",
        categoria: "Bulbo",
        humedad: "Media-Baja",
        meses: [3,4,5,6],
        estacion: "Otoño-Invierno",
        germina: 12,
        cosecha: 120,
        macetaMin: "20cm",
        macetaIdeal: "25cm",
        tips: "No encharcar el sustrato.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Cebolla de Verdeo",
        categoria: "Bulbo",
        humedad: "Media",
        meses: [2,3,4,5,6,7,8,9],
        estacion: "Otoño-Primavera",
        germina: 10,
        cosecha: 70,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Muy útil para corte frecuente.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Ajo",
        categoria: "Bulbo",
        humedad: "Baja",
        meses: [4,5,6],
        estacion: "Otoño-Invierno",
        germina: 15,
        cosecha: 150,
        macetaMin: "20cm",
        macetaIdeal: "25cm",
        tips: "Plantar dientes separados.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Puerro",
        categoria: "Bulbo",
        humedad: "Media",
        meses: [3,4,5,6,7],
        estacion: "Otoño-Invierno",
        germina: 12,
        cosecha: 110,
        macetaMin: "20cm",
        macetaIdeal: "25cm",
        tips: "Tolera bien el frío.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Repollo",
        categoria: "Comestible",
        humedad: "Media",
        meses: [3,4,5,6],
        estacion: "Otoño-Invierno",
        germina: 7,
        cosecha: 120,
        macetaMin: "25cm",
        macetaIdeal: "30cm",
        tips: "Le gusta clima fresco.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Coliflor",
        categoria: "Comestible",
        humedad: "Media",
        meses: [3,4,5,6],
        estacion: "Otoño-Invierno",
        germina: 8,
        cosecha: 110,
        macetaMin: "25cm",
        macetaIdeal: "30cm",
        tips: "Necesita buen aporte de nutrientes.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Brócoli",
        categoria: "Comestible",
        humedad: "Media",
        meses: [3,4,5,6],
        estacion: "Otoño-Invierno",
        germina: 7,
        cosecha: 100,
        macetaMin: "25cm",
        macetaIdeal: "30cm",
        tips: "Produce mejor con clima fresco.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Apio",
        categoria: "Comestible",
        humedad: "Alta",
        meses: [2,3,4,8,9],
        estacion: "Otoño-Primavera",
        germina: 15,
        cosecha: 120,
        macetaMin: "20cm",
        macetaIdeal: "25cm",
        tips: "Necesita riego parejo.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Perejil",
        categoria: "Aromática",
        humedad: "Media",
        meses: [2,3,4,5,6,7,8],
        estacion: "Otoño-Invierno",
        germina: 20,
        cosecha: 70,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Germinación lenta, paciencia.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Cilantro",
        categoria: "Aromática",
        humedad: "Media",
        meses: [2,3,4,5,6,7,8],
        estacion: "Otoño-Invierno",
        germina: 8,
        cosecha: 50,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Sube rápido a flor con calor.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Orégano",
        categoria: "Aromática",
        humedad: "Baja",
        meses: [3,4,5,9,10],
        estacion: "Primavera-Otoño",
        germina: 10,
        cosecha: 90,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Prefiere sol pleno.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Tomillo",
        categoria: "Aromática",
        humedad: "Baja",
        meses: [3,4,5,9,10],
        estacion: "Primavera-Otoño",
        germina: 14,
        cosecha: 90,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Muy resistente y poco exigente.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Salvia",
        categoria: "Aromática",
        humedad: "Baja-Media",
        meses: [3,4,5,9,10],
        estacion: "Primavera-Otoño",
        germina: 15,
        cosecha: 100,
        macetaMin: "20cm",
        macetaIdeal: "25cm",
        tips: "Necesita buena luz.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Melissa",
        categoria: "Aromática",
        humedad: "Media",
        meses: [3,4,5,9,10],
        estacion: "Primavera-Otoño",
        germina: 12,
        cosecha: 80,
        macetaMin: "20cm",
        macetaIdeal: "25cm",
        tips: "Muy buena para infusiones.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Ciboulette",
        categoria: "Aromática",
        humedad: "Media",
        meses: [2,3,4,5,6,7,8,9],
        estacion: "Otoño-Primavera",
        germina: 10,
        cosecha: 70,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Se puede cosechar por cortes.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Manzanilla",
        categoria: "Medicinal",
        humedad: "Baja-Media",
        meses: [3,4,5,8,9],
        estacion: "Primavera-Otoño",
        germina: 8,
        cosecha: 90,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Flores útiles para infusiones.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Aloe Vera",
        categoria: "Medicinal",
        humedad: "Baja",
        meses: [1,2,3,9,10,11,12],
        estacion: "Todo el año",
        germina: "",
        cosecha: "",
        macetaMin: "20cm",
        macetaIdeal: "25cm",
        tips: "Suculenta, regar poco.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Cedrón",
        categoria: "Medicinal",
        humedad: "Media",
        meses: [3,4,5,9,10],
        estacion: "Primavera-Otoño",
        germina: 15,
        cosecha: 100,
        macetaMin: "25cm",
        macetaIdeal: "30cm",
        tips: "Muy aromático, ideal para infusiones.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Tagete",
        categoria: "Flor / Decorativa",
        humedad: "Media",
        meses: [8,9,10,11],
        estacion: "Primavera-Verano",
        germina: 7,
        cosecha: 70,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Ayuda a repeler algunas plagas.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Petunia",
        categoria: "Flor / Decorativa",
        humedad: "Media",
        meses: [8,9,10],
        estacion: "Primavera",
        germina: 10,
        cosecha: 90,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Floración abundante si recibe sol.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Clavelina",
        categoria: "Flor / Decorativa",
        humedad: "Baja-Media",
        meses: [3,4,5,8,9],
        estacion: "Primavera-Otoño",
        germina: 10,
        cosecha: 100,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Muy buena para balcones soleados.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Copete",
        categoria: "Flor / Decorativa",
        humedad: "Media",
        meses: [8,9,10,11],
        estacion: "Primavera-Verano",
        germina: 7,
        cosecha: 75,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Aporta color y atrae polinizadores.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Capuchina",
        categoria: "Flor / Decorativa",
        humedad: "Media",
        meses: [8,9,10],
        estacion: "Primavera",
        germina: 8,
        cosecha: 80,
        macetaMin: "20cm",
        macetaIdeal: "25cm",
        tips: "Flor comestible y muy decorativa.",
        imgEtapa1: "",
        imgEtapa2: ""
    }
];