const plantas = [

{
nombre: "Acelga",
categoria: "Comestible",
humedad: "Media-Alta",
meses: [1,2,3,4,5,6,7,8,9,10],
estacion: "Todo el año",
germina: 8,
cosecha: 70,
macetaMin: "20cm prof.",
macetaIdeal: "30cm (15L)",
tips: "Cosecha hojas externas. Alta en nitrógeno.",
imgEtapa1: "/img/plantas/acelga-1.jpg",
imgEtapa2: "/img/plantas/acelga-2.jpg"
},

{
nombre: "Ajo",
categoria: "Bulbo",
humedad: "Baja",
meses: [4,5,6],
estacion: "Otoño-Invierno",
germina: 15,
cosecha: 150,
macetaMin: "20cm",
macetaIdeal: "25cm",
tips: "Plantar dientes separados.",
imgEtapa1: "/img/plantas/ajo-1.jpg",
imgEtapa2: "/img/plantas/ajo-2.jpg"
},

{
nombre: "Albahaca",
categoria: "Aromática",
humedad: "Media",
meses: [9,10,11,12],
estacion: "Verano",
germina: 6,
cosecha: 60,
macetaMin: "15cm",
macetaIdeal: "20cm",
tips: "No soporta frío.",
imgEtapa1: "/img/plantas/albahaca-1.jpeg",
imgEtapa2: "/img/plantas/albahaca-2.jpeg"
},

{
nombre: "Apio",
categoria: "Comestible",
humedad: "Alta",
meses: [2,3,4,8,9],
estacion: "Otoño-Primavera",
germina: 15,
cosecha: 120,
macetaMin: "20cm",
macetaIdeal: "25cm",
tips: "Necesita riego parejo.",
imgEtapa1: "/img/plantas/apio-1.jpg",
imgEtapa2: "/img/plantas/apio-2.jpg"
},

{
nombre: "Arveja",
categoria: "Leguminosa",
humedad: "Media",
meses: [3,4,5,6,7],
estacion: "Otoño-Invierno",
germina: 7,
cosecha: 80,
macetaMin: "20cm",
macetaIdeal: "25cm",
tips: "Necesita tutor liviano.",
imgEtapa1: "/img/plantas/arveja-1.jpg",
imgEtapa2: "/img/plantas/arveja-2.jpg"
},

{
nombre: "Berenjena",
categoria: "Fruto",
humedad: "Media",
meses: [8,9,10],
estacion: "Primavera",
germina: 10,
cosecha: 100,
macetaMin: "25cm",
macetaIdeal: "20L",
tips: "Mucho sol.",
imgEtapa1: "/img/plantas/berenjena-1.jpg",
imgEtapa2: "/img/plantas/berenjena-2.jpg"
},

{
nombre: "Brócoli",
categoria: "Comestible",
humedad: "Media",
meses: [3,4,5,6],
estacion: "Otoño-Invierno",
germina: 7,
cosecha: 100,
macetaMin: "25cm",
macetaIdeal: "30cm",
tips: "Prefiere clima fresco.",
imgEtapa1: "/img/plantas/brocoli-1.jpg",
imgEtapa2: "/img/plantas/brocoli-2.jpg"
},

{
nombre: "Caléndula",
categoria: "Flor / Decorativa",
humedad: "Baja-Media",
meses: [2,3,4,5,6,7,8],
estacion: "Otoño-Invierno",
germina: 10,
cosecha: 90,
macetaMin: "20cm",
macetaIdeal: "25cm",
tips: "Atrae polinizadores.",
imgEtapa1: "/img/plantas/calendula-1.jpg",
imgEtapa2: "/img/plantas/calendula-2.jpg"
},

{
nombre: "Cebolla",
categoria: "Bulbo",
humedad: "Media-Baja",
meses: [3,4,5,6],
estacion: "Otoño-Invierno",
germina: 12,
cosecha: 120,
macetaMin: "20cm",
macetaIdeal: "25cm",
tips: "No encharcar.",
imgEtapa1: "/img/plantas/cebolla-1.jpg",
imgEtapa2: "/img/plantas/cebolla-2.jpg"
},

{
nombre: "Cilantro",
categoria: "Aromática",
humedad: "Media",
meses: [2,3,4,5,6,7,8],
estacion: "Otoño-Invierno",
germina: 8,
cosecha: 50,
macetaMin: "15cm",
macetaIdeal: "20cm",
tips: "Sube rápido a flor con calor.",
imgEtapa1: "/img/plantas/cilantro-1.jpg",
imgEtapa2: ""
},

{
nombre: "Espinaca",
categoria: "Comestible",
humedad: "Media",
meses: [3,4,5,6,7,8],
estacion: "Invierno",
germina: 7,
cosecha: 50,
macetaMin: "15cm",
macetaIdeal: "20cm",tips: "Ideal clima frío.",
imgEtapa1: "/img/plantas/espinaca-1.jpg",
imgEtapa2: "/img/plantas/espinaca-2.jpg"
},

{
nombre: "Frutilla",
categoria: "Fruto",
humedad: "Media",
meses: [3,4,5,6],
estacion: "Otoño",
germina: 14,
cosecha: 120,
macetaMin: "15cm",
macetaIdeal: "20cm",
tips: "Ideal colgantes.",
imgEtapa1: "/img/plantas/frutilla-1.jpg",
imgEtapa2: "/img/plantas/frutilla-2.jpg"
},

{
nombre: "Girasol",
categoria: "Flor / Decorativa",
humedad: "Media",
meses: [9,10,11],
estacion: "Verano",
germina: 7,
cosecha: 90,
macetaMin: "30cm",
macetaIdeal: "40cm",
tips: "Sol pleno.",
imgEtapa1: "/img/plantas/girasol-1.jpg",
imgEtapa2: "/img/plantas/girasol-2.jpg"
},

{
nombre: "Lavanda",
categoria: "Flor / Decorativa",
humedad: "Baja",
meses: [3,4,9],
estacion: "Primavera",
germina: 15,
cosecha: 120,
macetaMin: "20cm",
macetaIdeal: "30cm",
tips: "Ama el sol.",
imgEtapa1: "/img/plantas/lavanda-1.jpg",
imgEtapa2: "/img/plantas/lavanda-2.jpg"
},

{
nombre: "Lechuga",
categoria: "Comestible",
humedad: "Media-Alta",
meses: [2,3,4,5,6,7,8,9],
estacion: "Otoño-Invierno",
germina: 5,
cosecha: 60,
macetaMin: "15cm",
macetaIdeal: "20cm",
tips: "Evitar calor fuerte.",
imgEtapa1: "/img/plantas/lechuga-1.jpg",
imgEtapa2: ""
},

{
nombre: "Menta",
categoria: "Aromática",
humedad: "Alta",
meses: [2,3,4,5,9,10],
estacion: "Primavera",
germina: 12,
cosecha: 60,
macetaMin: "20cm",
macetaIdeal: "25cm",
tips: "Muy invasiva.",
imgEtapa1: "/img/plantas/menta-1.jpeg",
imgEtapa2: ""
},

{
nombre: "Pepino",
categoria: "Fruto",
humedad: "Media-Alta",
meses: [9,10,11],
estacion: "Verano",
germina: 5,
cosecha: 70,
macetaMin: "25cm",
macetaIdeal: "30L",
tips: "Necesita tutor.",
imgEtapa1: "/img/plantas/pepino-1.jpg",
imgEtapa2: "/img/plantas/pepino-2.jpg"
},

{
nombre: "Perejil",
categoria: "Aromática",
humedad: "Media",
meses: [2,3,4,5,6,7,8],
estacion: "Otoño-Invierno",
germina: 20,
cosecha: 70,
macetaMin: "15cm",
macetaIdeal: "20cm",
tips: "Germinación lenta.",
imgEtapa1: "/img/plantas/perejil-1.jpg",
imgEtapa2: "/img/plantas/perejil-2.jpg"
},

{
nombre: "Remolacha",
categoria: "Raíz",
humedad: "Media",
meses: [2,3,4,5,6,7],
estacion: "Otoño",
germina: 8,
cosecha: 80,
macetaMin: "20cm",
macetaIdeal: "25cm",
tips: "También hojas comestibles.",
imgEtapa1: "/img/plantas/remolacha-1.jpg",
imgEtapa2: "/img/plantas/remolacha-2.jpg"
},

{
nombre: "Romero",
categoria: "Aromática",
humedad: "Baja",
meses: [3,4,5,9],
estacion: "Todo el año",
germina: 20,
cosecha: 120,
macetaMin: "20cm",
macetaIdeal: "30cm",
tips: "Muy resistente.",
imgEtapa1: "/img/plantas/romero-1.jpg",
imgEtapa2: "/img/plantas/romero-2.jpg"
},

{
nombre: "Rúcula",
categoria: "Comestible",
humedad: "Media",
meses: [2,3,4,5,6,7,8,9],
estacion: "Otoño-Primavera",
germina: 4,
cosecha: 40,
macetaMin: "10cm",
macetaIdeal: "15cm",
tips: "Muy rápida.",
imgEtapa1: "/img/plantas/rucula-1.jpg",
imgEtapa2: "/img/plantas/rucula-2.jpg"
},

{
nombre: "Tomate",
categoria: "Fruto",
humedad: "Media",
meses: [8,9,10,11],
estacion: "Primavera-Verano",
germina: 7,
cosecha: 90,
macetaMin: "30cm",
macetaIdeal: "20L",
tips: "Mucho sol.",
imgEtapa1: "/img/plantas/tomate-1.jpg",
imgEtapa2: "/img/plantas/tomate-2.jpg"
},

{
nombre: "Zanahoria",
categoria: "Raíz",
humedad: "Media",
meses: [3,4,5,6,7,8],
estacion: "Invierno",
germina: 10,
cosecha: 90,
macetaMin: "25cm",
macetaIdeal: "30cm",
tips: "Tierra suelta.",
imgEtapa1: "/img/plantas/zanahoria-1.jpg",
imgEtapa2: "/img/plantas/zanahoria-2.jpg"
},
{
        nombre: "Papa",
        categoria: "Tubérculo",
        humedad: "Media",
        meses: [8,9,10],
        estacion: "Primavera",
        germina: 15,
        cosecha: 120,
        macetaMin: "30cm",
        macetaIdeal: "Bolsa 40L",
        tips: "Conviene aporcar a medida que crece.",
        imgEtapa1: "/img/plantas/papa-1.jpg",
        imgEtapa2: "/img/plantas/papa-2.jpg"
    },
    {
        nombre: "Batata",
        categoria: "Tubérculo",
        humedad: "Media",
        meses: [10,11,12],
        estacion: "Verano",
        germina: 15,
        cosecha: 140,
        macetaMin: "30cm",
        macetaIdeal: "40L",
        tips: "Necesita bastante calor.",
        imgEtapa1: "/img/plantas/batata-1.jpg",
        imgEtapa2: "/img/plantas/batata-2.jpg"
    },{
        nombre: "Cebolla de Verdeo",
        categoria: "Bulbo",
        humedad: "Media",
        meses: [2,3,4,5,6,7,8,9],
        estacion: "Otoño-Primavera",
        germina: 10,
        cosecha: 70,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Muy útil para corte frecuente.",
        imgEtapa1: "/img/plantas/cebollaverdeo-1.jpg ",
          imgEtapa2: ""
      },{
        nombre: "Puerro",
        categoria: "Bulbo",
        humedad: "Media",
        meses: [3,4,5,6,7],
        estacion: "Otoño-Invierno",
        germina: 12,
        cosecha: 110,
        macetaMin: "20cm",
        macetaIdeal: "25cm",
        tips: "Tolera bien el frío.",
        imgEtapa1: "/img/plantas/puerro-1.jpeg",
        imgEtapa2: "/img/plantas/puerro-2.jpg"
    },
    {
        nombre: "Repollo",
        categoria: "Comestible",
        humedad: "Media",
        meses: [3,4,5,6],
        estacion: "Otoño-Invierno",
        germina: 7,
        cosecha: 120,
        macetaMin: "25cm",
        macetaIdeal: "30cm",
        tips: "Le gusta clima fresco.",
        imgEtapa1: "/img/plantas/repollo-1.jpg",
        imgEtapa2: "/img/plantas/repollo-2.jpg"
    },
    {
        nombre: "Coliflor",
        categoria: "Comestible",
        humedad: "Media",
        meses: [3,4,5,6],
        estacion: "Otoño-Invierno",
        germina: 8,
        cosecha: 110,
        macetaMin: "25cm",
        macetaIdeal: "30cm",
        tips: "Necesita buen aporte de nutrientes.",
        imgEtapa1: "/img/plantas/coliflor-1.jpg",
        imgEtapa2: "/img/plantas/coliflor-2.jpg"
    },
    {
        nombre: "Orégano",
        categoria: "Aromática",
        humedad: "Baja",
        meses: [3,4,5,9,10],
        estacion: "Primavera-Otoño",
        germina: 10,
        cosecha: 90,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Prefiere sol pleno.",
        imgEtapa1: "/img/plantas/oregano-1.jpg",
        imgEtapa2: "/img/plantas/oregano-2.jpg"
    },
    {
        nombre: "Tomillo",
        categoria: "Aromática",
        humedad: "Baja",
        meses: [3,4,5,9,10],
        estacion: "Primavera-Otoño",
        germina: 14,
        cosecha: 90,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Muy resistente y poco exigente.",
        imgEtapa1: "/img/plantas/tomillo-1.jpg",
        imgEtapa2: "/img/plantas/tomillo-2.jpg"
    },
    {
        nombre: "Salvia",
        categoria: "Aromática",
        humedad: "Baja-Media",
        meses: [3,4,5,9,10],
        estacion: "Primavera-Otoño",
        germina: 15,
        cosecha: 100,
        macetaMin: "20cm",
        macetaIdeal: "25cm",
        tips: "Necesita buena luz.",
        imgEtapa1: "/img/plantas/salvia-1.jpg",
        imgEtapa2: "/img/plantas/salvia-2.jpg"
    },
    {
        nombre: "Melissa",
        categoria: "Aromática",
        humedad: "Media",
        meses: [3,4,5,9,10],
        estacion: "Primavera-Otoño",
        germina: 12,
        cosecha: 80,
        macetaMin: "20cm",
        macetaIdeal: "25cm",
        tips: "Muy buena para infusiones.",
        imgEtapa1: "/img/plantas/melissa-1.jpg",
        imgEtapa2: "/img/plantas/melissa-2.jpg"
    },
    {
        nombre: "Ciboulette",
        categoria: "Aromática",
        humedad: "Media",
        meses: [2,3,4,5,6,7,8,9],
        estacion: "Otoño-Primavera",
        germina: 10,
        cosecha: 70,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Se puede cosechar por cortes.",
        imgEtapa1: "/img/plantas/ciboulette-1.jpg",
        imgEtapa2: "/img/plantas/ciboulette-2.jpg"
    },
    {
        nombre: "Manzanilla",
        categoria: "Medicinal",
        humedad: "Baja-Media",
        meses: [3,4,5,8,9],
        estacion: "Primavera-Otoño",
        germina: 8,
        cosecha: 90,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Flores útiles para infusiones.",
        imgEtapa1: "/img/plantas/manzanilla-1.jpg",
        imgEtapa2: "/img/plantas/manzanilla-2.jpg"
    },
    {
        nombre: "Aloe Vera",
        categoria: "Medicinal",
        humedad: "Baja",
        meses: [1,2,3,9,10,11,12],
        estacion: "Todo el año",
        germina: "",
        cosecha: "",
        macetaMin: "20cm",
        macetaIdeal: "25cm",
        tips: "Suculenta, regar poco.",
        imgEtapa1: "/img/plantas/aloe-1.jpg",
        imgEtapa2: "/img/plantas/aloe-2.jpg"
    },
    {
        nombre: "Cedrón",
        categoria: "Medicinal",
        humedad: "Media",
        meses: [3,4,5,9,10],
        estacion: "Primavera-Otoño",
        germina: 15,
        cosecha: 100,
        macetaMin: "25cm",
        macetaIdeal: "30cm",
        tips: "Muy aromático, ideal para infusiones.",
        imgEtapa1: "/img/plantas/cedron-1.jpg",
        imgEtapa2: "/img/plantas/cedron-2.jpg"
    },
    {
        nombre: "Tagete",
        categoria: "Flor",
        humedad: "Media",
        meses: [8,9,10,11],
        estacion: "Primavera-Verano",
        germina: 7,
        cosecha: 70,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Ayuda a repeler algunas plagas.",
        imgEtapa1: "/img/plantas/tagetes-1.jpg",
        imgEtapa2: "/img/plantas/tagetes-2.jpg"
    },
    {
        nombre: "Petunia",
        categoria: "Flor",
        humedad: "Media",
        meses: [8,9,10],
        estacion: "Primavera",
        germina: 10,
        cosecha: 90,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Floración abundante si recibe sol.",
        imgEtapa1: "/img/plantas/petunia-1.jpg ",
        imgEtapa2: "/img/plantas/petunia-2.jpg "
    },
    {
        nombre: "Clavelina",
        categoria: "Flor",
        humedad: "Baja-Media",
        meses: [3,4,5,8,9],
        estacion: "Primavera-Otoño",
        germina: 10,
        cosecha: 100,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Muy buena para balcones soleados.",
        imgEtapa1: "/img/plantas/clavelina-1.jpg",
        imgEtapa2: "/img/plantas/clavelina-2.jpg "
    },
    {
        nombre: "Copete",
        categoria: "Flor",
        humedad: "Media",
        meses: [8,9,10,11],
        estacion: "Primavera-Verano",
        germina: 7,
        cosecha: 75,
        macetaMin: "15cm",
        macetaIdeal: "20cm",
        tips: "Aporta color y atrae polinizadores.",
        imgEtapa1: "",
        imgEtapa2: ""
    },
    {
        nombre: "Capuchina",
        categoria: "Flor",
        humedad: "Media",
        meses: [8,9,10],
        estacion: "Primavera",
        germina: 8,
        cosecha: 80,
        macetaMin: "20cm",
        macetaIdeal: "25cm",
        tips: "Flor comestible y muy decorativa.",
        imgEtapa1: "/img/plantas/capuchina-1.jpg",
        imgEtapa2: "/img/plantas/capuchina-2.jpg"
    },
    

  // ===== FRUTOS DE HUERTA =====
  {
    nombre: "Sandía",
    categoria: "Fruto",
    humedad: "Media",
    meses: [9,10,11,12],
    germina: 7,
    cosecha: 90,
    macetaMin: "40cm prof",
    tips: "Pleno sol",
    imagen: "sandia.jpg"
  },
  {
    nombre: "Melón",
    categoria: "Fruto",
    humedad: "Media",
    meses: [9,10,11],
    germina: 6,
    cosecha: 80,
    macetaMin: "40cm prof",
    tips: "Pleno sol",
    imgEtapa1: "/img/plantas/melon-1.jpg",
    imgEtapa2: "/img/plantas/melon-2.jpg" 
  },
  {
    nombre: "Morrón",
    categoria: "Fruto",
    humedad: "Media",
    meses: [8,9,10],
    germina: 10,
    cosecha: 90,
    macetaMin: "30cm prof",
    tips: "Pleno sol",
    imgEtapa1: "/img/plantas/morron-1.jpg",
    imgEtapa2: "/img/plantas/morron-2.jpg",
  },

  // ===== ÁRBOLES FRUTALES =====
  {
    nombre: "Naranjo",
    categoria: "Frutal árbol",
    humedad: "Media",
    meses: [3,4,5,6],
    germina: "",
    cosecha: 365,
    macetaMin: "Grande (mín 60L)",
    tips: "Pleno sol",
    imgEtapa1: "/img/plantas/naranjo-1.jpg",
    imgEtapa2: ""
  },
  {
    nombre: "Limonero",
    categoria: "Frutal árbol",
    humedad: "Media",
    meses: [3,4,5,6],
    germina: "",
    cosecha: 365,
    macetaMin: "Grande (mín 60L)",
    tips: "Pleno sol",
    imgEtapa1: "/img/plantas/limonero-1.jpg",
    imgEtapa2: "/img/plantas/limonero-2.jpg",
  },
  {
    nombre: "Peral",
    categoria: "Frutal árbol",
    humedad: "Media",
    meses: [6,7,8],
    germina: "",
    cosecha: 365,
    macetaMin: "Suelo o maceta muy grande",
    tips: "Pleno sol",
    imgEtapa1: "/img/plantas/peras-1.jpg",
    imgEtapa2: "/img/plantas/peras-2.jpg"
  },
  {
    nombre: "Higuera",
    categoria: "Frutal árbol",
    humedad: "Baja",
    meses: [6,7,8],
    germina: "",
    cosecha: 365,
    macetaMin: "Grande",
    tips: "Pleno sol",
    imgEtapa1: "/img/plantas/higuera-1.jpg",
    imgEtapa2: "/img/plantas/higuera-2.jpg"
  },
  {
    nombre: "Membrillo",
    categoria: "Frutal árbol",
    humedad: "Media",
    meses: [6,7],
    germina: "",
    cosecha: 365,
    macetaMin: "Suelo o grande",
    tips: "Pleno sol",
    imgEtapa1: "/img/plantas/membrillo-1.jpg",
    imgEtapa2: "/img/plantas/membrillo-2.jpg"
  },
  {
    nombre: "Manzano",
    categoria: "Frutal árbol",
    humedad: "Media",
    meses: [6,7,8],
    germina: "",
    cosecha: 365,
    macetaMin: "Suelo o grande",
    tips: "Pleno sol",
    imgEtapa1: "/img/plantas/manzana-1.jpg",
    imgEtapa2: "/img/plantas/manzana-2.jpg"
  },
  {
    nombre: "Duraznero",
    categoria: "Frutal árbol",
    humedad: "Media",
    meses: [6,7,8],
    germina: "",
    cosecha: 365,
    macetaMin: "Suelo",
    tips: "Pleno sol",
    imgEtapa1: "/img/plantas/durazno-1.jpg",
    imgEtapa2: "/img/plantas/durazno-2.jpg"
  },
  {
    nombre: "Ciruelo",
    categoria: "Frutal árbol",
    humedad: "Media",
    meses: [6,7,8],
    germina: "",
    cosecha: 365,
    macetaMin: "Suelo",
    tips: "Pleno sol",
    imgEtapa1: "/img/plantas/ciruelo-1.jpg",
    imgEtapa2: "/img/plantas/ciruelo-2.jpg"
  }


];

